---
all:
  children:
    arista:
      hosts:
        arista1:
          ansible_host: 192.168.1.1
    emsfp:
      children:
        st2110_10G_dec:
          hosts:
            decap_device_1:
              ansible_host_ip: 192.168.1.100
            decap_device_2:
              ansible_host_ip: 192.168.1.102
        st2110_10G_enc:
          hosts:
            encap_device_1:
              ansible_host_ip: 192.168.1.101
            encap_device_2:
              ansible_host_ip: 192.168.1.103
        Embox3:
          hosts:
            box3_1:
              ansible_host_ip: 10.168.2.50
            box3_2:
              ansible_host_ip: 10.168.2.51
        Embox6:
          hosts:
            box6_1:
              ansible_host_ip: 192.168.2.150
            box6_2:
              ansible_host_ip: 192.168.2.151