# Playbook embox-sdi.yml
#
# This playbook configures embox6 sdi parameters from inventory values.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars:
    - ansible_python_interpreter: /usr/bin/env python

  tasks:
    - name: Get Modules configuration from the generated YML file.
      include_vars: ipconfigs_payload.yml
      check_mode: no
      changed_when: no

    - name: loop over modules
      include_tasks: embox-sdi-block.yml