# Playbook embox-port.yml
#
# This playbook configures embox6 port parameters from inventory values.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: emsfp
  gather_facts: no
  vars_files:
      - common_vars/all/all.yml
      - common_vars/box/all.yml
  vars:
    - ansible_python_interpreter: /usr/bin/env python

  tasks:
    - set_fact:
        workflow_type: inventory

    - name: Get module type
      emsfp_get_type_2:
        ip_addr: "{{ hostvars[inventory_hostname].ansible_host_ip }}"
      register: module_info
      delegate_to: localhost
      tags: always

    - name: Configure ports from inventory
      include_tasks: snippets/snippet-port.yml
      loop: "{{ embrionix_module.parameters.port | default({}) | dict2items }}"
