# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: all
  gather_facts: no
  vars:
    - ansible_python_interpreter: "{{ lookup('env','VIRTUAL_ENV') }}/bin/python"

  tasks: 
    - name: Pousser la configuration
      emsfp_reset_configs:
        ip_addr: "{{ ipconfig.Target }}"
        reboot: "{{ reboot }}"
        config_reset: "{{ config_reset }}"
      connection: local