# Playbook emsfp-ipconfig.yml
#
# This playbook configures ip parameters from inventory values.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: all
  gather_facts: no
  vars:
    - ansible_python_interpreter: "{{ lookup('env','VIRTUAL_ENV') }}/bin/python"

  tasks:
    - name: create reachable_hosts group.
      import_tasks: snippets/snippet-list-reachable-hosts.yml

    - name: Configure flows
      import_tasks: snippets/snippet-ipconfig.yml
      when: "'reachable_hosts' in group_names"