# Valid csv columns:
#   ip_addr,SDI1_AudMap
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars:
    var_file: "csv/config-file.csv"

  tasks: 
    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml_sdi_audio_mapping.j2"
        dest: "vars/sdi_audio_configs_payload.yml"
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/python
      run_once: true
      check_mode: no
      changed_when: no
  
    - name: Importer les valeurs de configuration à partir du fichier yaml.
      include_vars: sdi_audio_configs_payload.yml
      check_mode: no
      changed_when: no

    # - debug:
    #     msg: "{{ modules_ipconfig_payload }}"

    - name: Pousser la configuration
      emsfp_dec_sdi_audio_output:
        ip_addr: "{{ item.ip_addr }}"
        sdi_channel_id: "{{ item.sdi_channel_id }}"
        ch0: "{{ item.sdi_ch0 }}"
        ch1: "{{ item.sdi_ch1 }}"
      loop: "{{ modules }}"