# Playbook emsfp-csv-framesync.yml
#
# This playbook configures Embrionix devices framesync parameters from values provided by a csv.
#
# Required csv columns:
# ip_addr, module_type, sdi_channel_id, frame_sync, offset_mode, usec_offset, v_offset, h_offset
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars:
      - var_file: "csv/config-file.csv"
      - ansible_python_interpreter: /usr/bin/env python

  tasks:
    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml.j2"
        dest: "vars/framesync_payload.yml"
        force: yes
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/env python
      run_once: true
      check_mode: no
      changed_when: no

    - name: Get Modules configuration from the generated YML file.
      include_vars: framesync_payload.yml
      check_mode: no
      changed_when: no

    - name: Pousser la configuration
      emsfp_line_offset:
        ip_addr: "{{ item.ip_addr | default(None) }}"
        module_type: "{{ item.module_type | default(None) }}"
        sdi_channel_id: "{{ item.sdi_channel_id | default(None) }}"
        frame_sync: "{{ item.frame_sync|bool | default(None) }}"
        offset_mode: "{{ item.offset_mode|bool | default(None) }}"
        usec_offset: "{{ item.usec_offset | default(None) }}"
        v_offset: "{{ item.v_offset | default(None) }}"
        h_offset: "{{ item.h_offset | default(None) }}"
      loop: "{{ modules | default(None) }}"
      delegate_to: localhost