# Playbook emsfp-add-modules-to-inventory-hosts.yml
#
# Description
#   Le playbook emsfp-add-modules-to-inventory-hosts.yml traite les lignes du csv ipconfig et ajoute les hosts dans le fichier host de l'inventaire visé.
#
# Utilisation
#   Le playbook peut être exécuté avec la commande suivante:
#     `ansible-playbook [nom du playbook] -i inventaire/[chemin du fichier d'inventaire] -l [machine ou groupe cible] -v`
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars_files:
    - common_vars/all/all.yml
  vars:
    - var_file: "csv/config-file.csv"
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - set_fact:
        workflow_type: csv

    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml.j2"
        dest: "vars/ipconfigs_payload.yml"
        force: yes
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/env python
      run_once: true
      check_mode: no
      changed_when: no

    - name: Get Modules configuration from the generated YML file.
      include_vars: ipconfigs_payload.yml

    - name: Update hosts inventory dict
      test_add_modules_to_hosts:
        parsed_modules_params: '{{ modules }}'
        inventory_hosts_path: '{{ inventory_base_path }}'
      register: new_hosts_inventory
      delegate_to: localhost


    - name: Modify the hosts file of the inventory
      copy:
        content: "{{ new_hosts_inventory.msg }}"
        dest: "{{ inventory_base_path }}/hosts.yml"
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Add the directives end marker at the beginning of the inventory file.
      lineinfile:
        path: "{{ inventory_base_path }}/hosts.yml"
        insertbefore: BOF
        line: "---"
      delegate_to: localhost
      when: not ansible_check_mode