# Playbook emsfp-config-download.yml
#
# Description
#   Le playbook emsfp-config-download.yml vise à télécharger les configurations d'un module emsfp dans un fichier yaml.
#
# Utilisation
#   Le playbook peut être exécuté avec la commande suivante:
#     `ansible-playbook [nom du playbook] -i inventaire/[chemin du fichier d'inventaire] -l [machine ou groupe cible] -v`
#
# Configuration des routes de l'api lues sur les modules emsfp
#
#   Liste des routes de configuration régulière :
#     Pour encapsulateurs et décapsulateurs :
#       /emsfp/node/v1/self/ipconfig/
#       /emsfp/node/v1/refclk/
#
#   Liste des routes de configuration basé sur un ID :
#     Appliquable à tous les types de module :
#       /emsfp/node/v1/flows/
#
#     Spécifique aux encapsulateurs :
#       /emsfp/node/v1/sdi_input/
#
#     Spécifique aux décapsulateurs :
#       /emsfp/node/v1/sdi_audio/
#       /emsfp/node/v1/sdi_output/
#
#   Liste des routes de configuration basées sur ID dans un parametre spécifique:
#     /emsfp/node/v1/refclk/ sous le parametre UUID
#
# Destination du fichier YAML
#
#   Le fichier est créé dans le répertoire ./vars/ et la nomenclature est "value_read_from_module_XXX.XXX.XXX.XXX".
#   Les X réprésentent l'adresse IP du module.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: emsfp
  gather_facts: no
  vars_files:
    - ../common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - name:
      emsfp_all_configs:
        ip_addr: "{{ ansible_host_ip }}"
        mode: download
      delegate_to: localhost
      register: downloaded_config
      vars:
        # - ansible_python_interpreter: "{{ lookup('env','VIRTUAL_ENV') }}/bin/python"
          - ansible_python_interpreter: "/usr/bin/env python"

    - name: Write temporary downloaded config to file
      copy:
        content: "{{ downloaded_config.msg }}"
        dest: "vars/values_read_from_module_{{ ansible_host_ip }}.yml"
      delegate_to: localhost
      when: not ansible_check_mode
      vars:
        - ansible_python_interpreter: "/usr/bin/python"