# Playbook emsfp-test-staging.yml
#
# This playbook is a test playbook
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: arista
  gather_facts: no
  vars:
    - ansible_connection: network_cli
    - ansible_network_os: eos
    - ansible_user: "{{ vault_arista_user }}"
    - ansible_password: "{{ vault_arista_pass }}"
    - smbus_list:
      - '05/04/0x51'
      - '05/05/0x51'

  tasks:
    # - debug: var=ansible_connection
    - name: Read the MAC on all module in the switch via the smbus. Only for MAC Procedure.
      eos_command:
        use_ssl: true
        commands:
          - enable
          - bash
          # Set the page 0x84 dans le registre 127 pour acceder a la MAC et au IP
          - smbus writes /scd/{{ item }} 127 0x84
          # Read 6 consecutive bytes from the register 133 (133-138) containing MAC address.
          - smbus reads /scd/{{ item }} 133 6
          - exit
      loop: "{{ smbus_list }}"

