# Playbook emsfp-reset-configs.yml
#
# This playbook resets the devices configurations usings values provided by a csv.
#
# Required csv columns:
# Target,reboot, config_reset
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars:
    var_file: "csv/config-file.csv"

  tasks: 
    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml.j2"
        dest: "vars/reset_payload.yml"
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/env python
      run_once: true
      check_mode: no
      changed_when: no

    - name: Importer les valeurs de configuration à partir du fichier yaml.
      include_vars: reset_payload.yml
      check_mode: no
      changed_when: no

    - name: Le payload est envoyé au module.
      emsfp_reset_configs:
        ip_addr: "{{ item.Target }}"
        reboot: "{{ item.reboot }}"
        config_reset: "{{ item.config_reset }}"
      loop: '{{ modules }}'