# Playbook emsfp-csv-sdi-audio-output.yml
#
# This playbook configures audio output parameters from values provided by a csv.
#
# Required csv columns:
# ip_addr,sdi_channel_id, sdi_ch0, sdi_ch1, sdi_ch2, sdi_ch3, sdi_ch4, sdi_ch5, sdi_ch6, sdi_ch7,
# sdi_ch8, sdi_ch9, sdi_ch10, sdi_ch11, sdi_ch12, sdi_ch13, sdi_ch14, sdi_ch15
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars:
    var_file: "csv/config-file.csv"

  tasks: 
    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml_sdi_audio_mapping.j2"
        dest: "vars/sdi_audio_configs_payload.yml"
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/python
      run_once: true
      check_mode: no
      changed_when: no
  
    - name: Importer les valeurs de configuration à partir du fichier yaml.
      include_vars: sdi_audio_configs_payload.yml
      check_mode: no
      changed_when: no

    # - debug:
    #     msg: "{{ modules_ipconfig_payload }}"

    - name: Pousser la configuration
      emsfp_dec_sdi_audio_output:
        ip_addr: "{{ item.ip_addr }}"
        sdi_channel_id: "{{ item.sdi_channel_id }}"
        ch0: "{{ item.sdi_ch0 }}"
        ch1: "{{ item.sdi_ch1 }}"
        ch2: "{{ item.sdi_ch2 }}"
        ch3: "{{ item.sdi_ch3 }}"
        ch4: "{{ item.sdi_ch4 }}"
        ch5: "{{ item.sdi_ch5 }}"
        ch6: "{{ item.sdi_ch6 }}"
        ch7: "{{ item.sdi_ch7 }}"
        ch8: "{{ item.sdi_ch8 }}"
        ch9: "{{ item.sdi_ch9 }}"
        ch10: "{{ item.sdi_ch10 }}"
        ch11: "{{ item.sdi_ch11 }}"
        ch12: "{{ item.sdi_ch12 }}"
        ch13: "{{ item.sdi_ch13 }}"
        ch14: "{{ item.sdi_ch14 }}"
        ch15: "{{ item.sdi_ch15 }}"
      loop: "{{ modules }}"