# Playbook emsfp-ptp.yml
#
# This playbook configures ptp parameters from inventory values.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: emsfp
  gather_facts: no
  vars_files:
    - common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - set_fact:
        workflow_type: inventory

    - name: create reachable_hosts group.
      import_tasks: snippets/snippet-list-reachable-hosts.yml

    - name: Configure ptp
      import_tasks: snippets/snippet-ptp.yml
      when: "'reachable_hosts' in group_names"