# Playbook emsfp-frame-sync.yml
#
# This playbook configures framesync parameters from inventory values.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: emsfp
  gather_facts: no
  vars_files:
    - common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - set_fact:
        workflow_type: inventory

    - name: Get module type
      emsfp_get_type_2:
        ip_addr: "{{ hostvars[inventory_hostname].ansible_host_ip }}"
      register: module_info
      delegate_to: localhost
      tags: always

    - debug:
        msg: "Le type: {{ module_info.type }}"
      delegate_to: localhost
      tags: always

    - name: DHCP is active
      emsfp_ipconfig:
        ip_addr:  "{{ hostvars[inventory_hostname].ansible_host_ip }}"
        dhcp_enable: "{{ ansible_param_dhcp }}"
      delegate_to: localhost
