# Pour chacun des encodeurs sfp, un numéro de licence spécifique au module doit être assigné à 
# la variable frame_sync_licence.
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: all
  gather_facts: no
  vars_files:
    - ../common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "{{ lookup('env','VIRTUAL_ENV') }}/bin/python"

  tasks:
    - name: Obtenir le type de module
      emsfp_get_type:
        ip_addr: "{{ hostvars[inventory_hostname].ansible_host_ip }}"
      delegate_to: localhost
      register: get_type

    - name: Enregistrer la licence frame_sync
      uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host_ip }}/emsfp/node/v1/self/license/"
        body: '{"feature": {"frame_sync": "{{frame_sync_licence}}"}}'
        body_format: json
        method: PUT
      delegate_to: localhost
      when:
        - get_type.type == "Encapsulator"
        - frame_sync_licence is defined
