# Playbook emsfp-csv-ptp.yml
#
# This playbook configures ptp parameters from values provided by a csv.
#
# Required csv columns:
# ip_addr,PTP_mode, ManualMode, PTP_domain_nb, PTP_VlanID, PTP_dscp
#
# These values must exists in the inventory:
# - emsfp_refclk_1
# - emsfp_refclk_2
#
# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: localhost
  gather_facts: no
  vars_files:
    - common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"
    - var_file: "csv/config-file.csv"

  tasks:
    - set_fact:
        workflow_type: csv

    - name: Conversion CSV vers YML.
      template:
        src: "templates/csv_to_yaml.j2"
        dest: "vars/ptp_payload.yml"
        force: yes
      vars: 
        - csvfile: "{{ lookup('file', '{{ var_file }}') }}"
        - ansible_python_interpreter: /usr/bin/env python
      run_once: true
      check_mode: no
      changed_when: no

    - name: Get Modules configuration from the generated YML file.
      include_vars: ptp_payload.yml
      check_mode: no
      changed_when: no

    - name: create reachable_hosts group.
      include_tasks: snippets/snippet-csv-list-reachable-hosts.yml

    - name: Pousser la configuration pour refclk
      emsfp_refclk:
        ip_addr: "{{ item.ip_addr }}"
        mode: "{{ item.PTP_mode }}"
        manual_ctrl: "{{ item.ManualMode }}"
      loop: "{{ modules }}"
      delegate_to: localhost
      when: item.ip_addr in reachable_hosts

    - name: Pousser la configuration pour refclk_id 1
      emsfp_refclk_id:
        ip_addr: "{{ item.ip_addr }}"
        reference_clock_id: "f2807dac-985d-11e5-8994-feff819cdc9f"
        domain_num: "{{ item.PTP_domain_nb }}"
        vlan_id: "{{ item.PTP_VlanID }}"
        dscp: "{{ item.PTP_dscp }}"
      loop: "{{ modules }}"
      delegate_to: localhost
      when: item.ip_addr in reachable_hosts

    - name: Pousser la configuration pour refclk_id 2
      emsfp_refclk_id:
        ip_addr: "{{ item.ip_addr }}"
        reference_clock_id: "f3807dac-985d-11e5-8994-feff819cdc9f"
        domain_num: "{{ item.PTP_domain_nb }}"
        vlan_id: "{{ item.PTP_VlanID }}"
        dscp: "{{ item.PTP_dscp }}"
      loop: "{{ modules }}"
      delegate_to: localhost
      when: item.ip_addr in reachable_hosts
