# Copyright: (c) 2018, Société Radio-Canada>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
#
---
- hosts: emsfp
  gather_facts: no
  vars_files:
    - common_vars/all/all.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - debug:
        msg: "{{ ansible_inventory_sources }}"